---
version: 2
root-markers:
  - .git/

provide-definition: true

tools:
  vim-vint: &vim-vint
    lint-command: "vint -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  eslint: &eslint
    lint-command: "./node_modules/.bin/eslint -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true

  prettier: &prettier
    format-command: "./node_modules/.bin/prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}"

  gprettier: &gprettier
    format-command: "prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}"

  jq: &jq
    format-command: "jq"

  shfmt: &shfmt
    format-command: "shfmt -ci -s -bn"
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: "shellcheck -f gcc -x -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  # luarocks install --local --server=https://luarocks.org/dev luaformatter

  lua-format: &lua-format
    format-command: 'lua-format -i'
    format-stdin: true

  black: &black
    format-command: "black -"
    format-stdin: true

  isort: &isort
    format-command: "isort --stdout -"
    format-stdin: true

  flake8: &flake8
    lint-command: "flake8 --config ~/.config/efm-langserver/flake8.toml --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  mypy: &mypy
    lint-command: "mypy"
    # lint-command: 'mypy --config-file ~/.config/efm-langserver/mypy.toml'
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  markdownlint: &markdownlint
    lint-command: "markdownlint -s -c ~/.config/efm-langserver/markdown.yaml"
    lint-stdin: true
    lint-formats:
      - "%f:%l %m"
      - "%f:%l:%c %m"
      - "%f: %l: %m"

  # nix-env -iA nixos.python3Packages.yamllint
  # pip install --user yamllint
  yamllint: &yamllint
    lint-command: "yamllint -c ~/.config/efm-langserver/yamllint.yaml -f parsable -"
    lint-stdin: true
    format-command: "prettier --stdin"
    format-stdin: true

  rustfmt: &rustfmt
    format-command: "cargo fmt -"
    format-stdin: true

  clippy: &clippy
    lint-command: "cargo clippy"

  vfmt: &vfmt
    format-command: "v fmt"

languages:
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *gprettier
    - <<: *yamllint
  jsonc:
    - <<: *gprettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  sh:
    - <<: *shfmt
    - <<: *shellcheck
  lua:
    - <<: *lua-format
  python:
    - <<: *black
    - <<: *isort
    - <<: *flake8
    - <<: *mypy
  markdown:
    - <<: *prettier
    - <<: *markdownlint
  vim:
    - <<: *vim-vint
  rust:
    - <<: *rustfmt
    - <<: *clippy
  vlang:
    - <<: *vfmt
