[character]
style_success = "cyan bold"
error_symbol = "✗"
use_symbol_for_status = true

[directory]
truncate_to_repo = false
truncation_length = 8

[git_branch]
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false

[gcloud]
disabled = true
