-- Suggestions can interfere with cmp
-- require("copilot").setup({
--   enabled = false,
--   suggestion = { enabled = false },
--   panel = { enabled = false },
-- })
-- require("copilot_cmp").setup({})
