{ config, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    autorandr
    androidStudioPackages.canary
    appimage-run
    betterdiscordctl
    betterlockscreen
    bitwarden
    cairo
    chromium
    darktable
    dbeaver
    deluge
    discord
    dolphin
    eclipses.eclipse-java
    emacs
    emacs-all-the-icons-fonts
    etcher
    exodus
    filezilla
    firefox
    flameshot
    fondo
    gdlauncher
    gimp
    gnome3.adwaita-icon-theme
    gnome3.gnome-disk-utility
    gnome3.networkmanagerapplet
    gnome3.pomodoro
    google-chrome-beta
    imwheel
    insomnia
    jetbrains.datagrip
    jetbrains.idea-ultimate
    keybase-gui
    krita
    lxappearance
    minecraft
    multimc
    nordic
    obs-studio
    okular
    pandoc
    pantheon.elementary-gtk-theme
    papirus-icon-theme
    picom
    pinta
    plex-media-player
    polybarFull
    pop-gtk-theme
    postman
    protontricks
    qutebrowser
    redshift
    signal-desktop
    sublime
    trilium-desktop
    via
    vimix-gtk-themes
    vlc
    vscode
    wally-cli
    xautolock
    xfce.thunar
    xfce.xfce4-notifyd
    xorg.xev
    xorg.xmodmap
    zoom-us
  ];
}
