{ config, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    acpi
    alacritty
    bat
    betterlockscreen
    binutils
    bitwarden
    brave
    clang
    clojure
    compton
    conda
    coursier
    crystal
    curl
    di
    discord
    docker
    docker-compose
    etcher
    exa
    exodus
    fd
    feh
    firefox
    flameshot
    fzf
    gimp
    git
    gitAndTools.hub
    glibc
    gnome3.gnome-disk-utility
    gnome3.networkmanagerapplet
    go
    google-chrome
    gotop
    gparted
    gradle
    htop
    insomnia
    jdk12
    jetbrains.idea-ultimate
    just
    keybase-gui
    keychain
    kitty
    kotlin
    ktlint
    lazydocker
    leiningen
    libpqxx
    libratbag
    libreoffice
    llvmPackages.libclang
    lxappearance-gtk3
    mergerfs
    mpv
    mypy
    ncdu
    neofetch
    neovim
    nix-index
    nixfmt
    nixpkgs-fmt
    nodejs-12_x
    ntfsprogs
    okular
    openjdk
    papirus-icon-theme
    parted
    pavucontrol
    piper
    postgresql
    qalculate-gtk
    ranger
    redshift
    ripgrep
    rofi
    rustup
    rxvt
    scry
    shards
    skim
    spotify
    starship
    unrar
    unzip
    vim
    wget
    woeusb
    xautolock
    xfce.thunar
    xfce4-14.xfce4-notifyd
    youtube-dl
    zafiro-icons
    zlib
    zsh
    zstd

    (
      python3.withPackages (
        ps:
          with ps; [
            beautifulsoup4
            black
            dbus-python
            flask
            jedi
            matplotlib
            mypy
            numpy
            pandas
            pygobject3
            pylint
            requests
            scipy
            virtualenvwrapper
          ]
      )
    )
  ];
  nixpkgs.overlays = [
    (
      self: super: {
        my-polybar = super.polybar.override {
          i3Support = true;
          pulseSupport = true;
        };
      }
    )
  ];
  nixpkgs.config.allowUnfree = true;
}
