#!/usr/bin/env python

import json
from typing import Any

import pandas as pd
from plumbum.cmd import jq, lsblk, zfs, zpool


def pp(v: Any):
    j = json.dumps(v)
    print((jq["-r"] << j)())


zfs_list: str = zpool["list", "-v", "-H", "-L", "-P"]()

drives = json.loads(
    lsblk["-J", "-o", "NAME,PATH,SIZE,VENDOR,MODEL,WWN,SERIAL,HCTL,KNAME"]()
)["blockdevices"]


# print(zfs_list)
used_drives_sn = set()
for d in drives:
    # pp(d["children"])
    if "children" in d:
        cds = d["children"]
        is_unused = True
        for cd in cds:
            if cd["kname"] in zfs_list:
                used_drives_sn.add(d["serial"])
                is_unused = False

seen_sn = set()
unused_drives = []
for d in drives:
    if d["serial"] not in used_drives_sn and d["serial"] not in seen_sn:
        if "children" in d:
            del d["children"]
        vendor_model = d["vendor"]
        if d["model"]:
            vendor_model = d["vendor"] + " " + d["model"]
        d["model"] = vendor_model
        del d["vendor"]
        unused_drives.append(d)
        seen_sn.add(d["serial"])

unused_drives.sort(key=lambda d: d["model"])
print(pd.DataFrame(unused_drives))

# vim: set ft=python:
