#!/usr/bin/env python

import json

import pandas as pd
from plumbum.cmd import lsblk

drives = json.loads(
    lsblk["-J", "-d", "-o", "NAME,PATH,SIZE,WWN,SERIAL,SUBSYSTEMS,VENDOR,MODEL,HCTL"]()
)["blockdevices"]

usb_devices = [d for d in drives if "scsi:usb" in d["subsystems"]]

print(pd.DataFrame(usb_devices))

# vim: set ft=python:
