#!/usr/bin/env python
import sh

print(sh.lsblk("-o", "NAME"))

# IFS=$'\n'
# OFS=$'\n'
#
# # printf '%s' $(lsblk -nro NAME,SIZE,WWN,MODEL,SERIAL,PATH,PARTLABEL,FSTYPE)
# disks="$(lsblk -ro NAME,SIZE,WWN,MODEL,SERIAL,PATH,PARTLABEL,FSTYPE | grep "ST14000NM0001" | awk '!seen[$5]++ { printf "%s # %s %s\n", $6, $5, $4 }')"
#
# printf $disks
#
# echo "Choose a drive (only the first drive of the pair is shown):"
#
# chosen_disk=$(echo $disks | gum choose --limit 1)
#
# echo $chosen_disk
